#!/bin/bash -ex

#Config Vars
NODE_URL="http://nodejs.org/dist/v0.10.21/node-v0.10.21.tar.gz"
NODE_TARGET="/tmp/"
NODE_V="node-v0.10.21"
GHOST_URL="https://github.com/TryGhost/Ghost.git"
GHOST_DIR="/opt/ghost"
#USERNAME="admin"
#PASSWORD="turnkey"

#python
easy_install pip
pip install py-bcrypt

#get node
wget $NODE_URL -P $NODE_TARGET
tar xvzf /tmp/$NODE_V.tar.gz -C $NODE_TARGET
cd $NODE_TARGET/$NODE_V && ./configure
cd $NODE_TARGET/$NODE_V && make
cd $NODE_TARGET/$NODE_V && make install

#install sqlite3 with npm
npm install sqlite3
#Install forever globally

#Get Ghost from git
git clone $GHOST_URL $GHOST_DIR
#install sass and bourbon with gem
cd $GHOST_DIR && gem install sass bourbon
#updates casper theme
cd $GHOST_DIR && git submodule update --init
cd $GHOST_DIR && npm install -g grunt-cli
cd $GHOST_DIR && npm install
cd $GHOST_DIR && grunt init
cd $GHOST_DIR && cp config.example.js config.js
cd $GHOST_DIR && npm install -g forever
chown -R www-data:www-data /opt/ghost

#ghost daemon
#chmod +x /etc/init.d/ghost
#update-rc.d ghost defaults
crontab /tmp/for_cron.txt

#start ghost
/usr/local/bin/ghost-starter.sh
killall node
#get db that is prepared for inithooks
mv /tmp/ghost-dev.db /opt/ghost/content/data/

#nginx site enable
ln -s /etc/nginx/sites-available/ghost /etc/nginx/sites-enabled/ghost
#disable default
rm /etc/nginx/sites-enabled/default
#stop service
/etc/init.d/nginx stop
