#!/bin/bash -ex

#Config Vars
GHOST_URL="https://ghost.org/zip/ghost-0.7.8.zip"
GHOST_DIR="/opt/ghost/"

# Get Ghost (Stable 0.7.8)
wget $GHOST_URL -O $GHOST_DIR
chown -R node:node $GHOST_DIR

#Set node version (0.10.40 confirmed to work)
cd $GHOST_DIR && npm install --production
mv /tmp/ghost-dev.db $GHOST_DIR/content/data/ghost.db

#nginx considerations
#ghost runs on 2368. Proxy to port 80 and port 443 (SSL/TLS)
ln -s /etc/nginx/sites-available/ghost /etc/nginx/sites-enabled/ghost
rm /etc/nginx/sites-enabled/default



# pm2
cd $GHOST_DIR && su node --command "pm2 ./index.js --name Ghost --env production"



#install sass and bourbon with gem
#cd $GHOST_DIR && gem install sass bourbon
#updates casper theme
#cd $GHOST_DIR && git submodule update --init
#cd $GHOST_DIR && npm install -g grunt-cli
#cd $GHOST_DIR && npm install --production
#cd $GHOST_DIR && grunt init
#cd $GHOST_DIR && grunt prod
#cd $GHOST_DIR && cp config.example.js config.js
#cd $GHOST_DIR && npm install -g forever
#chown -R www-data:www-data $GHOST_DIR

#ghost daemon
#chmod +x /etc/init.d/ghost
#update-rc.d ghost defaults
#crontab /tmp/for_cron.txt

#start ghost
#/usr/local/bin/ghost-starter.sh
#killall node
#killall node
#get db that is prepared for inithooks

#nginx site enable
#ln -s /etc/nginx/sites-available/ghost /etc/nginx/sites-enabled/ghost
#disable default
#rm /etc/nginx/sites-enabled/default
#stop service
#/etc/init.d/nginx stop
